server:
  port: 9021 #端口
spring:
  zipkin:
    base-url: http://192.168.16.177:9081/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

  application:
    name: api-gateway-server #服务名称
  cloud:
    gateway:
      routes:
      - id: service-order
        #uri: http://127.0.0.1:9002 #固定ip
        uri: lb://service-order
        predicates:
        #- Path=/order/**  #200
        - Path=/test/** #404
        filters:
        - RewritePath=/test/(?<segment>.*), /$\{segment}  #路径重写
       #同上配置二选一.和rotes同级
      discovery:
        locator:
          enabled: true  #PS:开启根据服务名称自动转发,http://127.0.0.1:9021/service-order/order/buy/1
          lower-case-service-id: true  #微服务名称小写

#配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true #使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG